### ISSUE TITLE
Question: why does ohm have its own json parsing lib?

### ISSUE THREAD

**Issue by rgrinberg** [VictorNicollet/Ohm#3]
Even an unpopular language like OCaml seems to have no shortage of json parsing libs (yojson for example), what is the reasoning for Ohm maintaining its own?

**Comment by VictorNicollet** [comment]
The design goals of `Yojson` do not match the actual needs of Ohm applications, and have led to a few choices that are actually inferior to `Ohm.Json` in the restricted context of using JSON in a web application. These are : 
1. Anything outside module `Yojson.Basic` is useless when you're communicating with third party code that uses standard JSON. Arguably, this could be solved by leaving the other modules alone, but... 
2. In order to support multiple modules, `Yojson` uses a polymorphic variant type to represent JSON values. This comes with a cost : error messages appear when a value is used instead of when it is constructed, which is often less readable and requires more experience of OCaml to deal with than standard variants. 
3. The `Yojson` default philosophy of &laquo; _If it has no decimals, it must be an integer_ &raquo; is detrimental in an ecosystem where both the database and many client-side JSON serialization libraries will not add an arbitrary `.0` suffix to floating-point numbers without a fractional part. In particular, writing large floating-point numbers to CouchDB requires some unsexy black magic to read them back reliably.
4. The `Yojson` documentation is huge, and a very small fraction of it is actually relevant to Ohm (these would be type `json`, `to_string` with no optional parameters, `from_string` with no optional parameters, and the `to_` functions from `Util`, all of these in `Yojson.Basic`). 

The `Ohm.Json` library itself is extremely simple, significantly less so that `Yojson` (a grand total of 220 lines of code), and is now frozen in terms of code and features &mdash; the maintenance cost of having the `Ohm.Json` library is insignificant.

**Comment by VictorNicollet** [comment]
As a small historical note, `Ohm` originally used json-wheel, and `Ohm.Json` was implemented to solve the &laquo; _If it has no decimals, it must be an integer_ &raquo; issue and provide 2&times; performance in the typical use case. At the same time, the `type json t` syntax extension was included in `Ohm` as a replacement for json-static that also fixed a few things while retaining the possibility (unlike Atdgen) to generate the serialization code from within the OCaml source files.

**Comment by rgrinberg** [comment]
Thanks for the detailed response Victor, I will close this issue since your answer is completely satisfactory.
