### ISSUE TITLE
May I change the database to mongodb or mysql else?

### ISSUE THREAD

**Issue by foreveryh** [VictorNicollet/Ohm#5]
Because I have no any experience in CouchDB, it's really a problem for me.

**Comment by VictorNicollet** [comment]
Sadly, I am not aware of any OCaml bindings for MongoDB (but if you find some, I can certainly point out how to integrate those with Ohm). For MySQL, there's [ocaml-mysql](http://ocaml-mysql.forge.ocamlcore.org/) possibly combined with [Macaque](http://macaque.forge.ocamlcore.org/).

There are very few dependencies between core Ohm modules and CouchDB - the only ones are the `Async` and `Reset` modules, and I can provide you with a tutorial on how to disable them if you wish.

**Comment by foreveryh** [comment]
Thank you for your quick reply. I don't have to use MonoDB, actually, I am not really familiar with NoSQL database. If you think CouchDB fits Ohm well, I am glad to accept it. By the way, I deployed Ohm successfully in my server even only a 404 page I got. I am ready to continue my OCaml study, and I wish to contribute Ohm if possible.

**Comment by VictorNicollet** [comment]
The 404 page is normal --- by default, there's nothing else to display, because you haven't started building anything yet. 

I believe CouchDB has a very interesting approach to persistent storage, and Ohm does a good enough job of abstracting away most of the nasty ugly parts of using it. The one part that I still haven't cleaned up is the CouchDB views, so if you're in the mood for combining Ohm and [CouchDB-OCaml-Adapter](https://github.com/VictorNicollet/CouchDB-OCaml-Adapter), I'm all for it. 

I am actually considering including an SQL connector in Ohm, and allowing users to pick one or the other, but that is more of a long-term project. I am certainly open to contributions in this area.

Please get back in touch with me if you have any other questions. I'm slowly writing the tutorials, but know what to write about first is very useful.
